name: Auto Merge PR

on:
  pull_request:
    branches:
      - main   # Trigger on PRs targeting the main branch
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Auto merge PR
        if: github.event.pull_request.merged == false
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
