name: Auto Merge PR

on:
  pull_request:
    types:
      - labeled  # Trigger when the PR is labeled
      - ready_for_review  # Trigger when the PR is marked ready for review
      - synchronize  # Trigger when the PR is updated

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Auto merge PR
        if: github.event.pull_request.merged == false
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
